/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface XLottie {
    'aspectRatio': string;
    'autoplay': boolean;
    'data': string;
    'destroy': () => Promise<void>;
    'infinite': boolean;
    'pause': () => Promise<void>;
    'progressive': boolean;
    'resume': () => Promise<void>;
  }
  interface XShowcase {}
}

declare global {


  interface HTMLXLottieElement extends Components.XLottie, HTMLStencilElement {}
  var HTMLXLottieElement: {
    prototype: HTMLXLottieElement;
    new (): HTMLXLottieElement;
  };

  interface HTMLXShowcaseElement extends Components.XShowcase, HTMLStencilElement {}
  var HTMLXShowcaseElement: {
    prototype: HTMLXShowcaseElement;
    new (): HTMLXShowcaseElement;
  };
  interface HTMLElementTagNameMap {
    'x-lottie': HTMLXLottieElement;
    'x-showcase': HTMLXShowcaseElement;
  }
}

declare namespace LocalJSX {
  interface XLottie {
    'aspectRatio'?: string;
    'autoplay'?: boolean;
    'data'?: string;
    'infinite'?: boolean;
    'progressive'?: boolean;
  }
  interface XShowcase {}

  interface IntrinsicElements {
    'x-lottie': XLottie;
    'x-showcase': XShowcase;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'x-lottie': LocalJSX.XLottie & JSXBase.HTMLAttributes<HTMLXLottieElement>;
      'x-showcase': LocalJSX.XShowcase & JSXBase.HTMLAttributes<HTMLXShowcaseElement>;
    }
  }
}


